name: home-heaven

services:
  home-heaven:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: home-heaven-db
    environment:
      MSSQL_SA_PASSWORD: Admin1234
      ACCEPT_EULA: Y
      MSSQL_PID: Evaluation
    ports:
      - "1433:1433"